# Shared defaults for all apps (Spring Cloud Config native repo)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.cloud.discovery.enabled=true
spring.kafka.bootstrap-servers=localhost:9092
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/event-app
