server.port=8084
spring.kafka.bootstrap-servers=localhost:9092
app.security.local-jwt.secret=your-256-bit-secret-key-for-jwt-signing
app.security.local-jwt.issuer=user-service-local
spring.data.mongodb.uri=mongodb://localhost:27017/reservationdb
