server.port=8088
spring.kafka.bootstrap-servers=localhost:9092
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/event-app
app.security.local-jwt.secret=your-256-bit-secret-key-for-jwt-signing
app.security.local-jwt.issuer=user-service-local
