spring.application.name=discovery-server
# Eureka doesn't need to fetch config from Config Server
# It uses local configuration only
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# Eureka Server Configuration
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=localhost
